# Generated by Django 5.2 on 2025-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('experience_years', models.IntegerField()),
                ('subject', models.CharField(choices=[('math', 'Math'), ('physics', 'Physics'), ('english', 'English')], max_length=25)),
            ],
        ),
    ]
